/*
 * This source file was generated by the Gradle 'init' task
 */
package org.avl;

public class Main {

    public static void main(String[] args) {
        AVLTree tree = new AVLTree();

        // Inserts four nodes into the tree
        tree.insert(3);
        tree.insert(4);
        tree.insert(5);
        tree.insert(6);

        // Prints out a serialized tree which might look like "4,3,5,nil,nil,nil,6""
        // The actual output will depend on the pattern you use to serialize the tree
        String s1 = tree.serialize();
        System.out.println(s1);
        // Deletes a node from the tree
        tree.remove(6);

        // Prints out a serialized tree which might look like "4,3,5"
        // The actual output will depend on the pattern you use to serialize the tree
        System.out.println(tree.serialize());
        Deserializer d = new Deserializer();

        //recreate first tree from first serialization
        AVLTree tree2 = d.deserialize(s1);
        System.out.println(tree2.serialize());
    }
}
